### PR TITLE
Handle rotation on map activity

### LINKED ISSUE #72: Rotating device on map view crashes
Rotating device to landscape when displaying map causes app to crash.

`
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gophillygo.app/com.gophillygo.app.activities.PlacesMapsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.model.Marker com.google.android.gms.maps.GoogleMap.addMarker(com.google.android.gms.maps.model.MarkerOptions)' on a null object reference
`

### PR DESCRIPTION
**Pull request by maurizi**
## Overview

Handles rotation events on the map activities by saving/restoring a few key properties (the selected attraction, whether we had already set the map location).

## Notes
I opted not to save/restore the current filters since that should be taken care of by #80 

Closes #72

### CODE REVIEW

File: app/src/main/java/com/gophillygo/app/activities/MapsActivity.java [hunk 1]
```diff
@@ -56,13 +56,15 @@
     private static final int DEFAULT_ZOOM = 12;
     private static final int ATTRACTION_ZOOM = 14;
     private static final float DEFAULT_OPACITY = 1f, FILTERED_OPACITY = 0.5f;
+    private static final String LOCATION_SET_KEY = "locationSet";
```
Comment (flibbertigibbet) [inline app/src/main/java/com/gophillygo/app/activities/MapsActivity.java]: Nitpick: these have been camel-cased everywhere else.

File: app/src/main/java/com/gophillygo/app/activities/MapsActivity.java [hunk 2]
```diff
@@ -84,17 +86,34 @@ protected void onCreate(Bundle savedInstanceState) {
         // Obtain the SupportMapFragment and get notified when the map is ready to be used.
         SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                 .findFragmentById(mapId);
+        if (savedInstanceState != null) {
+            locationSet = savedInstanceState.getBoolean(LOCATION_SET_KEY);
```
Comment (flibbertigibbet) [inline app/src/main/java/com/gophillygo/app/activities/MapsActivity.java]: Should guard this with a check to see if the key exists first.

File: app/src/main/java/com/gophillygo/app/activities/MapsActivity.java [hunk 3]
```diff
@@ -56,13 +56,15 @@
...
+    private static final String LOCATION_SET_KEY = "locationSet";
     private static final String LOG_LABEL = "MapsActivity";
+
     public static final String X = "x";
     public static final String Y = "y";
     public static final String ATTRACTION_ID = "id";
 
     private Map<Integer, Marker> markers;
-    private Marker selectedMarker;
+    private Integer selectedAttractionId = null;
```
Comment (flibbertigibbet) [inline app/src/main/java/com/gophillygo/app/activities/MapsActivity.java]: How about we make this a primitive and default for -1 as a flag value for being unset; that's what we're doing elsewhere.
