### PR TITLE
Bugfix/kak/fix parsing events with unpublished destination#178

### LINKED ISSUE #178: Event with unpublished destination fails to parse
API parsing of events data fails on encountering an event that has exactly one, unpublished destination.

image

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Fixes #178 

## Demo

Screenshot_1581547495

## Testing

 - uninstall app if previously installed (to force a fresh API request)
 - run app
 - should have no logged errors
 - all events should load (not just one)

### CODE REVIEW

File: app/src/main/java/org/gophillygo/app/data/models/Event.java [hunk 1]
```diff
@@ -105,7 +105,7 @@ public Integer getDestination() {
 
     public void setDestination(Integer id) {
         // Hide destination if there is more than one
```
Comment (maurizi) [inline app/src/main/java/org/gophillygo/app/data/models/Event.java]:
```suggestion
        // Hide destination if there are none, or if there is more than one
```
